{
 "title": "internet usage graph",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Bandwith Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "aliasByNode(internet_usage.*.received, 1)"
    }
   ]
  },
  {
   "title": "Received Data",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(integral(internet_usage.*.received), 1)"
    }
   ]
  },
  {
   "title": "Total usage",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "target": "integral(sumSeriesWithWildcards(internet_usage.*.received, 1))"
    }
   ]
  }
 ]
}